apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ow4eb1z4j-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ow4eb1z4j-nodejs 
  name: ow4eb1z4j-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: ow4eb1z4j-nodejs 
